In [2]:
# Importing the libraries
import matplotlib.pyplot as plt  
import pandas as pd  
%matplotlib inline
import numpy as np

In [3]:
#load csv file
dengue_train_data = pd.read_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\dengue_features_train.csv')

In [4]:
#check rows and column length
dengue_train_data.shape

(1456, 25)

In [5]:
# view few rows of data
dengue_train_data.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
0,sj,1990,18,30/04/1990,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
1,sj,1990,19,07/05/1990,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
2,sj,1990,20,14/05/1990,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
3,sj,1990,21,21/05/1990,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
4,sj,1990,22,28/05/1990,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6

In [6]:
dengue_train_data.isnull().sum()

city                                       0
year                                       0
weekofyear                                 0
week_start_date                            0
ndvi_ne                                  194
ndvi_nw                                   52
ndvi_se                                   22
ndvi_sw                                   22
precipitation_amt_mm                      13
reanalysis_air_temp_k                     10
reanalysis_avg_temp_k                     10
reanalysis_dew_point_temp_k               10
reanalysis_max_air_temp_k                 10
reanalysis_min_air_temp_k                 10
reanalysis_precip_amt_kg_per_m2           10
reanalysis_relative_humidity_percent      10
reanalysis_sat_precip_amt_mm              13
reanalysis_specific_humidity_g_per_kg     10
reanalysis_tdtr_k                         10
station_avg_temp_c                        43
station_diur_temp_rng_c                   43
station_max_temp_c                        20
station_min_temp_c                        14
station_precip_mm                         22
total_cases                                0
dtype: int64

In [7]:
dengue_train_data.dtypes

city                                      object
year                                       int64
weekofyear                                 int64
week_start_date                           object
ndvi_ne                                  float64
ndvi_nw                                  float64
ndvi_se                                  float64
ndvi_sw                                  float64
precipitation_amt_mm                     float64
reanalysis_air_temp_k                    float64
reanalysis_avg_temp_k                    float64
reanalysis_dew_point_temp_k              float64
reanalysis_max_air_temp_k                float64
reanalysis_min_air_temp_k                float64
reanalysis_precip_amt_kg_per_m2          float64
reanalysis_relative_humidity_percent     float64
reanalysis_sat_precip_amt_mm             float64
reanalysis_specific_humidity_g_per_kg    float64
reanalysis_tdtr_k                        float64
station_avg_temp_c                       float64
station_diur_temp_rng_c                  float64
station_max_temp_c                       float64
station_min_temp_c                       float64
station_precip_mm                        float64
total_cases                                int64
dtype: object

In [8]:
dengue_train_data['city'] = dengue_train_data['city'].astype('category') 
dengue_train_data['city'] = dengue_train_data['city'].cat.codes

dengue_train_data['week_start_date'] = dengue_train_data['week_start_date'].astype('category') 
dengue_train_data['week_start_date'] = dengue_train_data['week_start_date'].cat.codes

In [9]:
dengue_train_data_correct = dengue_train_data.fillna(dengue_train_data.mean()) 
dengue_train_data_correct.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
0,1,1990,18,1013,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
1,1,1990,19,221,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
2,1,1990,20,463,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
3,1,1990,21,705,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
4,1,1990,22,947,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6

In [10]:
dengue_train_data_correct.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
total_cases                              0
dtype: int64

In [11]:
y = dengue_train_data_correct['total_cases']
dengue_train_data_correct_features = dengue_train_data_correct.drop(['total_cases'], 1)
X = dengue_train_data_correct_features

In [12]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, r2_score

#test_train_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2852, random_state=101)
#logreg
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

y_pred = regr.predict(X_test)


# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean absoulute error: %.2f"
      % mean_absolute_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients:
 [-2.73619785e+00 -1.83916394e+00  5.26541043e-01 -4.89311168e-03
  2.57160897e+00  1.01391709e+01 -2.20812304e+01  1.90684587e+01
 -4.03557298e-03  1.82041240e+00 -6.29287325e-01 -1.78259134e+01
  6.45042292e-01 -1.26021126e+00 -7.81607163e-03 -8.38141141e-01
 -4.03557298e-03  2.27146128e+01 -3.78341693e+00 -2.73147419e+00
 -1.49009219e+00  3.02367631e+00  8.15889352e-02  1.84952404e-03]
Mean absoulute error: 19.48
Variance score: 0.14

In [13]:
dengue_test_data = pd.read_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\dengue_features_test.csv')

In [170]:
dengue_test_data.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,2008,18,2008-04-29,-0.0189,-0.018900,0.102729,0.091200,78.60,298.492857,...,25.37,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2
1,sj,2008,19,2008-05-06,-0.0180,-0.012400,0.082043,0.072314,12.56,298.475714,...,21.83,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3
2,sj,2008,20,2008-05-13,-0.0015,NaN,0.151083,0.091529,3.66,299.455714,...,4.12,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0
3,sj,2008,21,2008-05-20,NaN,-0.019867,0.124329,0.125686,0.00,299.690000,...,2.20,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3
4,sj,2008,22,2008-05-27,0.0568,0.039833,0.062267,0.075914,0.76,299.780000,...,4.36,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1

In [14]:
dengue_test_data.shape

(416, 24)

In [15]:
dengue_test_data.isnull().sum()

city                                      0
year                                      0
weekofyear                                0
week_start_date                           0
ndvi_ne                                  43
ndvi_nw                                  11
ndvi_se                                   1
ndvi_sw                                   1
precipitation_amt_mm                      2
reanalysis_air_temp_k                     2
reanalysis_avg_temp_k                     2
reanalysis_dew_point_temp_k               2
reanalysis_max_air_temp_k                 2
reanalysis_min_air_temp_k                 2
reanalysis_precip_amt_kg_per_m2           2
reanalysis_relative_humidity_percent      2
reanalysis_sat_precip_amt_mm              2
reanalysis_specific_humidity_g_per_kg     2
reanalysis_tdtr_k                         2
station_avg_temp_c                       12
station_diur_temp_rng_c                  12
station_max_temp_c                        3
station_min_temp_c                        9
station_precip_mm                         5
dtype: int64

In [16]:
dengue_test_data['city'] = dengue_test_data['city'].astype('category') 
dengue_test_data['city'] = dengue_test_data['city'].cat.codes

dengue_test_data['week_start_date'] = dengue_test_data['week_start_date'].astype('category') 
dengue_test_data['week_start_date'] = dengue_test_data['week_start_date'].cat.codes

In [17]:
dengue_test_data_correct = dengue_test_data.fillna(dengue_test_data.mean()) 
dengue_test_data_correct.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

In [18]:
regr_1 = linear_model.LinearRegression()
regr_1.fit(X, y)
y_pred_1 = regr_1.predict(dengue_test_data_correct)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(y_test, y_pred_1))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred_1))

Coefficients:
 [-2.73619785e+00 -1.83916394e+00  5.26541043e-01 -4.89311168e-03
  2.57160897e+00  1.01391709e+01 -2.20812304e+01  1.90684587e+01
 -4.03557298e-03  1.82041240e+00 -6.29287325e-01 -1.78259134e+01
  6.45042292e-01 -1.26021126e+00 -7.81607163e-03 -8.38141141e-01
 -4.03557298e-03  2.27146128e+01 -3.78341693e+00 -2.73147419e+00
 -1.49009219e+00  3.02367631e+00  8.15889352e-02  1.84952404e-03]
Mean absolute error: 22.83
Variance score: -0.27

In [19]:
Acutal_and_Predicted_data = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_1})
Acutal_and_Predicted_data

      Actual  Predicted
18        24  15.549309
104       24  12.480645
373        7  14.298855
1225      10  16.909057
342       29  20.695620
460       37  19.967909
1251       2  20.632515
1334      25  24.968347
230      395  26.757547
1065      11  26.216879
846       16  22.255222
925        6  24.649504
567       19  29.326858
757       15  25.685346
690       25  32.794647
486       21  35.060471
856       11  33.209036
651        6  35.839640
1381      29  41.032864
524        2  40.949847
754       20  34.873666
0          4  33.685134
1342       3  40.043260
723       11  33.071704
60        18  35.543824
559       17  31.150942
132       34  30.102940
1209       2  33.151605
198       31  29.087519
778        1  31.474896
...      ...        ...
957        0  22.072657
744       14  10.760370
955        0  12.224266
1229      24  18.519486
674        7  -6.263835
909       68 -20.340005
100       30 -13.705387
439      127 -12.882905
515        3  -0.363632
268       10 -12.525449
1083       1  -8.612820
1119       5  -4.008264
34        27  -8.588484
339       30  -6.362039
583       14  -9.163916
118       33   4.910884
285       36  -8.340341
1042       4 -13.125493
1177       6 -14.101100
829        1   1.103461
933        1   2.074900
1295       8 -19.683448
919       15  -3.255095
1255       2  -0.807549
742       20  -2.465857
850       15  -7.867531
985        0  -7.226943
972        0 -11.940665
875       18 -17.481022
693       32 -19.675850

[416 rows x 2 columns]

In [20]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)
RFR.fit(X, y)
Y_predicted_by_RFR = RFR.predict(dengue_test_data_correct)
print('Mean Absolute Error:', mean_absolute_error(y_test, Y_predicted_by_RFR))

Mean Absolute Error: 18.475448214445994

In [21]:
Acutal_and_Predicted_data = pd.DataFrame({'Actual': y_test, 'Predicted': Y_predicted_by_RFR})
Acutal_and_Predicted_data

      Actual  Predicted
18        24  10.311875
104       24  10.311875
373        7  10.311875
1225      10  10.311875
342       29  10.591573
460       37  11.219880
1251       2  10.759333
1334      25  10.759333
230      395  17.094993
1065      11  15.344922
846       16  15.993716
925        6  15.344922
567       19  20.956878
757       15  25.734223
690       25  26.338110
486       21  43.091180
856       11  22.827534
651        6  41.870890
1381      29  43.091180
524        2  30.917429
754       20  26.920998
0          4  11.737459
1342       3  10.960385
723       11  24.754222
60        18  11.737459
559       17  11.737459
132       34  11.950901
1209       2  11.737459
198       31  11.737459
778        1  11.737459
...      ...        ...
957        0  10.311875
744       14  10.311875
955        0  10.311875
1229      24  10.311875
674        7  10.311875
909       68  10.311875
100       30  10.311875
439      127  10.311875
515        3  10.311875
268       10  10.311875
1083       1  10.311875
1119       5  10.311875
34        27  10.311875
339       30  10.311875
583       14  10.311875
118       33  10.311875
285       36  10.311875
1042       4  10.311875
1177       6  10.311875
829        1  10.311875
933        1  10.311875
1295       8  10.311875
919       15  10.311875
1255       2  10.311875
742       20  10.311875
850       15  10.311875
985        0  10.311875
972        0  10.311875
875       18  10.311875
693       32  10.311875

[416 rows x 2 columns]

In [22]:
df_test = pd.read_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\dengue_features_test.csv')
df_test.shape

(416, 24)

In [23]:
df_test = df_test.iloc[:, 0:3]
df_test['total_cases'] = Y_predicted_by_RFR
df_test['total_cases'] = df_test['total_cases'].astype(int)
df_test

    city  year  weekofyear  total_cases
0     sj  2008          18           10
1     sj  2008          19           10
2     sj  2008          20           10
3     sj  2008          21           10
4     sj  2008          22           10
5     sj  2008          23           11
6     sj  2008          24           10
7     sj  2008          25           10
8     sj  2008          26           17
9     sj  2008          27           15
10    sj  2008          28           15
11    sj  2008          29           15
12    sj  2008          30           20
13    sj  2008          31           25
14    sj  2008          32           26
15    sj  2008          33           43
16    sj  2008          34           22
17    sj  2008          35           41
18    sj  2008          36           43
19    sj  2008          37           30
20    sj  2008          38           26
21    sj  2008          39           11
22    sj  2008          40           10
23    sj  2008          41           24
24    sj  2008          42           11
25    sj  2008          43           11
26    sj  2008          44           11
27    sj  2008          45           11
28    sj  2008          46           11
29    sj  2008          47           11
..   ...   ...         ...          ...
386   iq  2012          48           10
387   iq  2012          49           10
388   iq  2012          50           10
389   iq  2012          51           10
390   iq  2013           1           10
391   iq  2013           2           10
392   iq  2013           3           10
393   iq  2013           4           10
394   iq  2013           5           10
395   iq  2013           6           10
396   iq  2013           7           10
397   iq  2013           8           10
398   iq  2013           9           10
399   iq  2013          10           10
400   iq  2013          11           10
401   iq  2013          12           10
402   iq  2013          13           10
403   iq  2013          14           10
404   iq  2013          15           10
405   iq  2013          16           10
406   iq  2013          17           10
407   iq  2013          18           10
408   iq  2013          19           10
409   iq  2013          20           10
410   iq  2013          21           10
411   iq  2013          22           10
412   iq  2013          23           10
413   iq  2013          24           10
414   iq  2013          25           10
415   iq  2013          26           10

[416 rows x 4 columns]

In [24]:
import math
submit = df_test
submit.to_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\submit_5.csv')

In [25]:
from sklearn.svm import SVR
regressor=SVR(kernel='linear')
xtrain,xtest,ytrain,ytest=train_test_split(X, y, test_size=0.2852)
regressor.fit(xtrain, ytrain)
pred = regressor.predict(xtest)
print(mean_absolute_error(ytest,pred))

18.467206366180754

In [26]:
regressor.fit(X, y)
pred_final = regressor.predict(dengue_test_data_correct)
print(mean_absolute_error(ytest,pred_final))

23.811326192545703

In [208]:
Acutal_and_Predicted_data = pd.DataFrame({'Actual': y_test, 'Predicted': pred_final})
Acutal_and_Predicted_data

      Actual  Predicted
18        24  11.717949
104       24  12.383107
373        7  12.466893
1225      10  11.411564
342       29  13.478561
460       37  16.082493
1251       2  17.126912
1334      25  16.446271
230      395  18.057422
1065      11  19.146763
846       16  17.571742
925        6  17.825149
567       19  18.598714
757       15  18.231594
690       25  21.689506
486       21  21.395389
856       11  21.132851
651        6  22.819770
1381      29  23.982442
524        2  24.403376
754       20  22.383007
0          4  22.855051
1342       3  22.734035
723       11  21.259435
60        18  21.632474
559       17  21.228550
132       34  20.668870
1209       2  21.749495
198       31  20.650230
778        1  20.893417
...      ...        ...
957        0  10.479802
744       14   7.191352
955        0  11.097974
1229      24  11.361890
674        7  -0.561791
909       68  -8.224770
100       30  -4.927928
439      127  -1.964977
515        3  -1.557091
268       10  -1.765644
1083       1   0.500617
1119       5   0.575475
34        27  -4.773405
339       30  -2.062207
583       14  -1.698873
118       33   4.159074
285       36   0.341299
1042       4  -2.382562
1177       6  -3.086545
829        1   0.763585
933        1   1.497733
1295       8  -7.287104
919       15   0.370351
1255       2   0.683529
742       20  -0.128351
850       15  -1.240693
985        0  -2.362108
972        0  -4.147795
875       18  -9.281389
693       32  -3.157267

[416 rows x 2 columns]

In [32]:
df_test_1 = pd.read_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\dengue_features_test.csv')
df_test_1.shape

(416, 24)

In [33]:
df_test_1 = df_test_1.iloc[:, 0:3]
df_test_1['total_cases'] = pred_final
df_test_1['total_cases'] = df_test_1['total_cases'].astype(int)
df_test_1

    city  year  weekofyear  total_cases
0     sj  2008          18           11
1     sj  2008          19           12
2     sj  2008          20           12
3     sj  2008          21           11
4     sj  2008          22           13
5     sj  2008          23           16
6     sj  2008          24           17
7     sj  2008          25           16
8     sj  2008          26           18
9     sj  2008          27           19
10    sj  2008          28           17
11    sj  2008          29           17
12    sj  2008          30           18
13    sj  2008          31           18
14    sj  2008          32           21
15    sj  2008          33           21
16    sj  2008          34           21
17    sj  2008          35           22
18    sj  2008          36           23
19    sj  2008          37           24
20    sj  2008          38           22
21    sj  2008          39           22
22    sj  2008          40           22
23    sj  2008          41           21
24    sj  2008          42           21
25    sj  2008          43           21
26    sj  2008          44           20
27    sj  2008          45           21
28    sj  2008          46           20
29    sj  2008          47           20
..   ...   ...         ...          ...
386   iq  2012          48           10
387   iq  2012          49            7
388   iq  2012          50           11
389   iq  2012          51           11
390   iq  2013           1            0
391   iq  2013           2           -8
392   iq  2013           3           -4
393   iq  2013           4           -1
394   iq  2013           5           -1
395   iq  2013           6           -1
396   iq  2013           7            0
397   iq  2013           8            0
398   iq  2013           9           -4
399   iq  2013          10           -2
400   iq  2013          11           -1
401   iq  2013          12            4
402   iq  2013          13            0
403   iq  2013          14           -2
404   iq  2013          15           -3
405   iq  2013          16            0
406   iq  2013          17            1
407   iq  2013          18           -7
408   iq  2013          19            0
409   iq  2013          20            0
410   iq  2013          21            0
411   iq  2013          22           -1
412   iq  2013          23           -2
413   iq  2013          24           -4
414   iq  2013          25           -9
415   iq  2013          26           -3

[416 rows x 4 columns]

In [34]:
submit = df_test
submit.to_csv(r'E:\MS Data Science\Semester 1\Tools and Techniques for Data Science\Project\imd\finalprojecttt\origianal data\submit_10.csv')

In [28]:
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_friedman1
from sklearn.ensemble import GradientBoostingRegressor


#Adaboost Regressor with Test Train data
adc_wiht_test_train = GradientBoostingRegressor()
adc_wiht_test_train.fit(X, y)
y_pred_reg = adc_wiht_test_train.predict(dengue_test_data_correct)
print ('Mean Absolute Error Using Adaboost Classifier Method: %f'%(mean_absolute_error(y_test,y_pred_reg)))

Mean Absolute Error Using Adaboost Classifier Method: 22.353996

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [ 728  729  730  731  732  733  734  735  736  737  738  739  740  741
  742  743  744  745  746  747  748  749  750  751  752  753  754  755
  756  757  758  759  760  761  762  763  764  765  766  767  768  769
  770  771  772  773  774  775  776  777  778  779  780  781  782  783
  784  785  786  787  788  789  790  791  792  793  794  795  796  797
  798  799  800  801  802  803  804  805  806  807  808  809  810  811
  812  813  814  815  816  817  818  819  820  821  822  823  824  825
  826  827  828  829  830  831  832  833  834  835  836  837  838  839
  840  841  842  843  844  845  846  847  848  849  850  851  852  853
  854  855  856  857  858  859  860  861  862  863  864  865  866  867
  868  869  870  871  872  873  874  875  876  877  878  879  880  881
  882  883  884  885  886  887  888  889  890  891  892  893  894  895
  896  897  898  899  900  901  902  903  904  905  906  907  908  909
  910  911  912  913  914  915  916  917  918  919  920  921  922  923
  924  925  926  927  928  929  930  931  932  933  934  935  936  937
  938  939  940  941  942  943  944  945  946  947  948  949  950  951
  952  953  954  955  956  957  958  959  960  961  962  963  964  965
  966  967  968  969  970  971  972  973  974  975  976  977  978  979
  980  981  982  983  984  985  986  987  988  989  990  991  992  993
  994  995  996  997  998  999 1000 1001 1002 1003 1004 1005 1006 1007
 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021
 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035
 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049
 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063
 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077
 1078 1079 1080 1081 1082 1083 1084 1085 1086 1087 1088 1089 1090 1091
 1092 1093 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1105
 1106 1107 1108 1109 1110 1111 1112 1113 1114 1115 1116 1117 1118 1119
 1120 1121 1122 1123 1124 1125 1126 1127 1128 1129 1130 1131 1132 1133
 1134 1135 1136 1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147
 1148 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161
 1162 1163 1164 1165 1166 1167 1168 1169 1170 1171 1172 1173 1174 1175
 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189
 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203
 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217
 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231
 1232 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245
 1246 1247 1248 1249 1250 1251 1252 1253 1254 1255 1256 1257 1258 1259
 1260 1261 1262 1263 1264 1265 1266 1267 1268 1269 1270 1271 1272 1273
 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1285 1286 1287
 1288 1289 1290 1291 1292 1293 1294 1295 1296 1297 1298 1299 1300 1301
 1302 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314 1315
 1316 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329
 1330 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343
 1344 1345 1346 1347 1348 1349 1350 1351 1352 1353 1354 1355 1356 1357
 1358 1359 1360 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370 1371
 1372 1373 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385
 1386 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399
 1400 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413
 1414 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427
 1428 1429 1430 1431 1432 1433 1434 1435 1436 1437 1438 1439 1440 1441
 1442 1443 1444 1445 1446 1447 1448 1449 1450 1451 1452 1453 1454 1455] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727]
Coefficients:
 [ 2.27900976e+00  4.13526626e-01  8.86115335e-02 -2.59462565e-03
  1.19637672e-01  2.51375753e-01 -8.22789654e+00  8.46119821e+00
  1.26362440e-02  7.48039556e+00 -5.73143240e+00 -1.09364106e+01
 -5.13229249e-02 -4.41364895e-01 -4.29147263e-02 -3.33181696e-01
  1.26362440e-02  1.50801892e+01 -1.74296375e-01  8.58782671e-01
 -1.55029198e+00  5.31697235e-01 -4.72038832e-01  6.68244772e-04]

ValueError: Found input variables with inconsistent numbers of samples: [728, 416]